"""update model

Revision ID: 6d7e952bde3a
Revises: e55d409b372b
Create Date: 2026-08-28 07:19:46.902602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d7e952bde3a'
down_revision: Union[str, Sequence[str], None] = 'e55d409b372b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_activities', 'priority',
               existing_type=mysql.ENUM('LOW', 'MEDIUM', 'HIGH'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_activities', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT'),
               type_=mysql.ENUM('LOW', 'MEDIUM', 'HIGH'),
               existing_nullable=False)
    # ### end Alembic commands ###
