"""update model

Revision ID: 88384b5bd444
Revises: 6d7e952bde3a
Create Date: 2026-08-28 08:23:26.438710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88384b5bd444'
down_revision: Union[str, Sequence[str], None] = '6d7e952bde3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_activities', 'assignee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('club_activities', 'priority',
               existing_type=mysql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_activities', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH'),
               type_=mysql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT'),
               existing_nullable=False)
    op.alter_column('club_activities', 'assignee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
